# Generated by Django 5.1.1 on 2024-09-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='upload_time',
            new_name='uploaded_at',
        ),
    ]
